os: linux
dist: bionic
language: python
python:
- '3.7'
addons:
  ssh_known_hosts:
  - "$HOSTNAME"
before_script:
- echo -e "Host $HOSTNAME\n\tStrictHostKeyChecking no" >> ~/.ssh/config
jobs:
  include:
  - stage: deploy
    if: branch = travis-testing AND type != pull_request
    script: skip
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_05d4d4358b2c_key -iv $encrypted_05d4d4358b2c_iv
      -in deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa
    deploy:
      provider: script
      skip_cleanup: true
      script: 
        scp -r $TRAVIS_BUILD_DIR TG-bot@$HOSTNAME:/home/TG-bot/travis-testing
        ssh -i /tmp/deploy_rsa TG-bot@$HOSTNAME "cd travis-testing && python3 main.py"
      on:
        branch: travis-testing
