version: "3.8"
services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    command: --label-enable --cleanup --interval 300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ssgbot:
    image: superserious/bot:latest
    # for dev
    # build: .
    volumes:
      - /db/:/db/
    env_file:
      - ssgbot.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  qbt:
    image: ghcr.io/linuxserver/qbittorrent