# Add tokens, keys, passwords, API creds, IDs and other personal info to this file

CLIMACELL_API_KEY: "apikey"
CLOUDMERSIVE_API_KEY: "apikey"
GOODREADS_API_KEY: "apikey"
JOGI_FILE_ID: "fileid"
MYSQL_ROOT_PASSWORD: "root_password"
MYSQL_DATABASE: "db_name"
MYSQL_USER: "username"
MYSQL_PASSWORD: "user_password"
MYSQL_IP_ALIAS: "mysql_ip_or_alias"
OPENWEATHER_API_KEY: "apikey"
TELEGRAM_BOT_TOKEN: "tokentokentoken"
WOLFRAM_APP_ID: "appid"
FOR_WHAT_ID: "fileid"
PUNYA_SONG_ID: "fileid"
AUDIO_RESTORE_USERS:
  - "username1"
  - "username2"
