# Add tokens, keys, passwords, API creds, IDs and other personal info to this file

CLIMACELL_API_KEY: "apikey"
CLOUDMERSIVE_API_KEY: "apikey"
GOODREADS_API_KEY: "apikey"
JOGI_FILE_ID: "fileid"
MYSQL_PW: "password"
MYSQL_USERNAME: "bot"
OPENWEATHER_API_KEY: "apikey"
TELEGRAM_BOT_TOKEN: "tokentokentoken"
WOLFRAM_APP_ID: "appid"
FOR_WHAT_ID: "fileid"
PUNYA_SONG_ID: "fileid"
AUDIO_RESTORE_USERS:
  - "username1"
  - "username2"
